parameters:
#    gb_creation_wall.example.class: GbCreation\WallBundle\Example

services:
#    gb_creation_wall.example:
#        class: %gb_creation_wall.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
