parameters:
#    gb_creation_home.example.class: GbCreation\HomeBundle\Example

services:
#    gb_creation_home.example:
#        class: %gb_creation_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
