parameters:
#    gb_creation_user.example.class: GbCreation\UserBundle\Example

services:
#    gb_creation_user.example:
#        class: %gb_creation_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
