parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: sy-wall
    database_user: root
    database_password: null
    mailer_transport: gmail
    mailer_host:      ~
    mailer_user: dev.gbe
    mailer_password: d3vPOINTgb3
    locale: fr
    secret: 0785425d87a16e7d57d79103a1650a85c
    database_path: null
