<?php

namespace GbCreation\WallBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{

	 public function getAllItems()
    {
        
      $query = $this->createQueryBuilder('i')
      ->orderBy('i.date', 'DESC')
      ->getQuery();
 
    	return $query->getResult();
    }

    public function getItemsWithComments()
    {
        
      $query = $this->createQueryBuilder('i')
      ->leftJoin('i.comments', 'c')
      ->addSelect('c')
      ->orderBy('i.date', 'DESC')
      ->getQuery();
 
    	return $query->getResult();
    }
}